"""empty message

Revision ID: 110d2e283fe0
Revises: ad03195464a0
Create Date: 2025-09-05 17:12:32.703704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '110d2e283fe0'
down_revision = 'ad03195464a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actuacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_personas', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cache', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('peticiones', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actuacion', schema=None) as batch_op:
        batch_op.drop_column('peticiones')
        batch_op.drop_column('cache')
        batch_op.drop_column('num_personas')

    # ### end Alembic commands ###
