"""empty message

Revision ID: 6906b4fdd37e
Revises: f506aedca8af
Create Date: 2025-08-25 10:04:21.812108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6906b4fdd37e'
down_revision = 'f506aedca8af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actuacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('escenario', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('hora_inicio', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('hora_fin', sa.Time(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actuacion', schema=None) as batch_op:
        batch_op.drop_column('hora_fin')
        batch_op.drop_column('hora_inicio')
        batch_op.drop_column('escenario')

    # ### end Alembic commands ###
