"""empty message

Revision ID: 7e2c9d3b29a0
Revises: 675dec3385b9
Create Date: 2025-09-08 08:31:40.551177

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7e2c9d3b29a0'
down_revision = '675dec3385b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actuacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('horario', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('num_personas', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cache', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('peticiones', sa.Text(), nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('hora_inicio',
               existing_type=postgresql.TIME(),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('hora_fin',
               existing_type=postgresql.TIME(),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.drop_column('hour')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actuacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hour', postgresql.TIME(), autoincrement=False, nullable=True))
        batch_op.alter_column('hora_fin',
               existing_type=sa.String(length=120),
               type_=postgresql.TIME(),
               existing_nullable=True)
        batch_op.alter_column('hora_inicio',
               existing_type=sa.String(length=120),
               type_=postgresql.TIME(),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.drop_column('peticiones')
        batch_op.drop_column('cache')
        batch_op.drop_column('num_personas')
        batch_op.drop_column('horario')

    # ### end Alembic commands ###
