"""empty message

Revision ID: d08552619d4d
Revises: a8b30f6f1f8e
Create Date: 2025-08-21 11:50:08.396178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd08552619d4d'
down_revision = 'a8b30f6f1f8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('puesto', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('card_number', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('card_cvc', sa.String(length=4), nullable=True))
        batch_op.add_column(sa.Column('card_expiration', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('card_holder', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('card_holder')
        batch_op.drop_column('card_expiration')
        batch_op.drop_column('card_cvc')
        batch_op.drop_column('card_number')
        batch_op.drop_column('puesto')

    # ### end Alembic commands ###
