"""empty message

Revision ID: d9321dc6a1b4
Revises: 
Create Date: 2025-09-08 10:44:49.022683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9321dc6a1b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actuacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.Column('horario', sa.String(length=120), nullable=True),
    sa.Column('escenario', sa.String(length=80), nullable=True),
    sa.Column('hora_inicio', sa.String(length=120), nullable=True),
    sa.Column('hora_fin', sa.String(length=120), nullable=True),
    sa.Column('num_personas', sa.Integer(), nullable=True),
    sa.Column('cache', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('peticiones', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('role', sa.Enum('ORGANIZADOR', 'PERSONAL', name='rolenum'), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.Column('horario', sa.String(length=120), nullable=True),
    sa.Column('puesto', sa.String(length=50), nullable=True),
    sa.Column('card_number', sa.String(length=16), nullable=True),
    sa.Column('card_cvc', sa.String(length=4), nullable=True),
    sa.Column('card_expiration', sa.String(length=7), nullable=True),
    sa.Column('card_holder', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('actuacion')
    # ### end Alembic commands ###
