"""empty message

Revision ID: f506aedca8af
Revises: 
Create Date: 2025-08-25 09:28:13.519642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f506aedca8af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actuacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.Column('hour', sa.Time(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('role', sa.Enum('ORGANIZADOR', 'PERSONAL', name='rolenum'), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.Column('puesto', sa.String(length=50), nullable=True),
    sa.Column('card_number', sa.String(length=16), nullable=True),
    sa.Column('card_cvc', sa.String(length=4), nullable=True),
    sa.Column('card_expiration', sa.String(length=7), nullable=True),
    sa.Column('card_holder', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('actuacion')
    # ### end Alembic commands ###
